### ISSUE TITLE
Bug in find_best_distribution Function

### ISSUE THREAD

**Issue by kotserge** [kicasta/Modeling_WUGS_WSBM#2]
I think there is a bug with your implementation of ```find_best_distribution```.

While you iterate over the possible distributions, you do not provide them as arguments for the ```minimize``` function.

Possible fix would be:

```py
def _find_best_distribution(graph: graph_tool.Graph):
     distributions = ["discrete-binomial", "discrete-geometric", "discrete-poisson"]
     best_distribution = ''
     best_state = None
     best_entropy = np.inf
     for distribution in distributions:
         state: BlockState = _minimize(graph, distribution=distribution, deg_corr=False)
         entropy = state.entropy(adjacency=False, degree_dl=False)
         if entropy < best_entropy:
             best_entropy = entropy
             best_distribution = distribution
             best_state = state

     return best_distribution, best_state
```

**Comment by kicasta** [comment]
I'll check it and come back to you as soon as I have time

**Comment by kicasta** [comment]
Somehow the distribution parameter was deleted while preparing the code to be published. Code will be updated in the repository accordingly and in the meantime all tests are been run, to re-check the presented results.
