### ISSUE TITLE
Example Notebook Paths

### ISSUE THREAD

**Issue by kotserge** [kicasta/Modeling_WUGS_WSBM#3]
In you Notebook you are using, I guess, absolute paths. 
Please use relative paths, as of currently this does not work on other machines.

Example fix:
```py
g_name = "zersetzen"
g_path = "wug_example/" + g_name
```

**Comment by kicasta** [comment]
Those paths in the notebook are for people that wanted to test things on colab.google.com without cloning the repository. It was desired add all files to the non permanent directory in "content/" that is created whenever you create a new session.
